### ISSUE TITLE
Resources device name in Pod spec

### ISSUE THREAD

**Issue by klin938** [intel/intel-device-plugins-for-kubernetes#1074]
Hi again,

In the demo, it has:

```
> kubectl describe node  |grep -A3 Allocatable                                                                                                                                    
Allocatable:                                                                                                                                                                      
  cpu:                                                     32                                                                                                                     
  ephemeral-storage:                                       94636958359                                                                                                            
  fpga.intel.com/region-69528db6eb31577a8c3668f9faa081f6:  2   
```

But inside the test-fpga-region.yaml, the specified device name is

```
fpga.intel.com/arria10.dcp1.2-nlb3-orchestrated: 1
```

I have watched the demo few times, could not figure it out where and how the name changed. 

On my own K8s cluster environment, I replaced the device name in Pod spec with the one from the Allocatable output, the webhook refused the request:
```
Error from server: error when creating "test-fpga-orchestrated.yaml": admission webhook "fpga.mutator.webhooks.intel.com" denied the request: no such resource: "fpga.intel.com/region-38d782e3b6125343b9342433e348ac4c"
```

Did I miss something?

Cheers
Derrick

**Comment by bart0sh** [comment]
It's changed by webhook according to the [mappings](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/deployments/fpga_admissionwebhook/mappings-collection.yaml#L115:L122).
You can change mappings to reflect your devices interface and AFU ids if they differ from those in the example collection.
Please find more details about mappings in the [webhook documentation](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/fpga_admissionwebhook/README.md#mappings).

Generally region(orchestration programmed) mode is much more difficult to setup. You can start from af(preprogrammed) mode if you just want to get familiar with the plugin.

**Comment by klin938** [comment]
Hi! I did change the mapping in the test-fpga-region.yaml to reflect what is mapped on our system.

I redeployed the plugin in af mode, new mapping name is generated. But the webhook still deny the resource request:

```
[root@r640-1-10 demo]# kubectl describe node  |grep -A3 Allocatable
--
Allocatable:
  cpu:                                                                    80
  ephemeral-storage:                                                      354306354614
  fpga.intel.com/af-38d.d84.ONeC47YSU0O5NCQz40isTNhCTcSko8QT-J5DNoP5BAs:  1
[root@r640-1-10 demo]# kubectl create -f test-fpga-preprogrammed.yaml
Error from server: error when creating "test-fpga-preprogrammed.yaml": admission webhook "fpga.mutator.webhooks.intel.com" denied the request: no such resource: "fpga.intel.com/af-38d.d84.onec47ysu0o5ncqz40istnhctcsko8qt-j5dnop5bas"
```
My pod yaml looks like:
```
[root@r640-1-10 demo]# cat test-fpga-preprogrammed.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-fpga-preprogrammed
spec:
  containers:
  - name: test-container
    image: intel/opae-nlb-demo:devel
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
          [IPC_LOCK]
    resources:
      limits:
        fpga.intel.com/af-38d.d84.ONeC47YSU0O5NCQz40isTNhCTcSko8QT-J5DNoP5BAs: 1
        cpu: 1
        hugepages-2Mi: 20Mi

  restartPolicy: Never
```
