### ISSUE TITLE
sgx: move to NFD extended resources via NodeFeatureRules

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#1380]
- [x] update NFD deployment to the latest release that brings the feature
- [x] create/update `NodeFeatureRule` for SGX EPC 
- [ ] drop SGX initcontainer from the default flows (or re-purpose it to be used with "epc -register")
- [x] update e2e test 
- [ ] update documentation

**Comment by mythi** [comment]
```
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sgx-epc-rule
spec:
  rules:
  - name: "SGX EPC"
    extendedResources:
      sgx.intel.com/epc: "@cpu.security.sgx.epc"
    matchFeatures:
      - feature: cpu.security
        matchExpressions:
          sgx.enabled: {op: IsTrue}
```
