### ISSUE TITLE
gpu: study and implement a way to limit Pod's i915 count

### ISSUE THREAD

**Issue by tkatila** [intel/intel-device-plugins-for-kubernetes#1408]
In #1377 it was identified that it would be required in some clusters to limit the Pod's i915 resource count to 1 (or some other value). The idea is to allow setting shared-dev-num to >1 and to prevent users from accessing more GPU resource than designed.

Webhook might be a good way to implement this, but it would be good to study other solutions as well.

**Comment by eero-t** [comment]
K8s supports limit ranges: https://kubernetes.io/docs/concepts/policy/limit-range/

@uniemimu thought that it should support extended resources in addition to core ones, but somebody needs to check (also) whether it actually works when one omits default and min values (i.e. whether it allows pods that do not request a GPU):
```
apiVersion: v1
kind: LimitRange
metadata:
  name: gpu-count-constraint
spec:
  limits:
  - max:
      gpu.intel.com/i915: 1
    type: Container
```
@uMartinXu can you try whether that does what you wanted?

**Comment by vbedida79** [comment]
Hi @eero-t, tried limitrange. supports extended resources.
It does not accept pods with `gpu.intel.com/i915 > 1`.  
`Warning  FailedCreate  2m55s  job-controller  Error creating: pods "intel-dgpu-clinfo-gphs2" is forbidden: maximum gpu.intel.com/i915 usage per Container is 1, but limit is 3
`
In case of a pods that do not request gpu resource- whether scheduled on GPU node or others, the pod does allocate i915 resource requests and limits:
```
LimitRanger plugin set: gpu.intel.com/i915 request for container httpd;
      gpu.intel.com/i915 limit for container httpd
```
```
containers:
    - resources:
        limits:
          gpu.intel.com/i915: '1'
        requests:
          gpu.intel.com/i915: '1'

```

**Comment by eero-t** [comment]
Thanks for testing!

Will it still try to add GPU resource requests for non-GPU pods, if you add:
```
min:
      gpu.intel.com/i915: 0
```
?

**Comment by vbedida79** [comment]
If default values are added to limitrange it is added to non GPU pods. If no default values are added to limit range, it allocates below values to non GPU pods. Is this expected?
```
- resources:
        limits:
          gpu.intel.com/i915: '1'
        requests:
          gpu.intel.com/i915: '1'
```

**Comment by vbedida79** [comment]
If default values are added to limitrange it is added to non GPU pods. If no default values are added to limit range, it allocates below values to non GPU pods. Is this expected?
```
- resources:
        limits:
          gpu.intel.com/i915: '1'
        requests:
          gpu.intel.com/i915: '1'
```
