### ISSUE TITLE
Intel SGX nodes not displaying expected EPC status values

### ISSUE THREAD

**Issue by phhutter** [intel/intel-device-plugins-for-kubernetes#1611]
Hi,

I'm having an issue where the epc values `status.capacity.sgx.intel.com/epc` and `status.allocatable.sgx.intel.com/epc` are missing from the nodes status section.

However, the following values are present:
```
kind: Node
[..]
status:
  capacity:
    sgx.intel.com/provision: '20'
    sgx.intel.com/enclave: '20'
[..]
  allocatable:
    sgx.intel.com/provision: '20'
    sgx.intel.com/enclave: '20'
```
There are no obvious error messages present in the idp/nfd DaemonSet logs, suggesting that the issue may probably reside within the NodeFeatureRule configuration ...

```
apiVersion: nfd.openshift.io/v1alpha1
kind: NodeFeatureRule
metadata:
  labels:
  name: example
  namespace: example
spec:
  rules:
    - labels:
        intel.feature.node.kubernetes.io/sgx: 'true'
      matchFeatures:
        - feature: cpu.cpuid
          matchExpressions:
            SGX:
              op: Exists
            SGXLC:
              op: Exists
        - feature: cpu.sgx
          matchExpressions:
            enabled:
              op: IsTrue
        - feature: kernel.config
          matchExpressions:
            X86_SGX:
              op: Exists
      name: intel.sgx
```
I've checked other github issues, and some time ago, another user reported a similar issue (https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1344)

I am using following software version in my test environment:
Kubernetes: v1.25.x
OpenShift: v4.12.x
Intel device plugin: 0.24.1
