### ISSUE TITLE
Allow custom tolerations with operator

### ISSUE THREAD

**Issue by cosandr** [intel/intel-device-plugins-for-kubernetes#1617]
Hi,

I'd like to deploy the gpu plugin with custom tolerations, i.e.

```yml
tolerations:
  - operator: "Exists"
    key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
```

but this doesn't appear to be possible. The [CRD](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/c5c1127620407eed71273b6336bd540106c272be/deployments/operator/crd/bases/deviceplugin.intel.com_gpudeviceplugins.yaml#L68) supports node selectors but not tolerations.

My workaround is deploying the daemonset with kustomize and patching it afterwards to have my tolerations, but I'd like to switch to the operator if possible. I admit I haven't tried to patch the daemonset deployed by the operator, I assumed that's a bad idea and that it would eventually replace it.
