### ISSUE TITLE
Eliminate FPGA admission webhook's mode

### ISSUE THREAD

**Issue by rojkov** [intel/intel-device-plugins-for-kubernetes#301]
Problem:

It is possible to run the FPGA device plugin in two different modes on different nodes of the same cluster. Yet the admission webhook can be aligned to work with FPGA device plugins in either preprogrammed or orchestrated mode. The webhook needs to be redesigned to be agnostic about the device plugins' modes. Also when operating in preprogrammed mode it is impossible to differentiate nodes providing the same accelerated function with different hardware, e.g. a user's request to dispatch a task onto `stratix10-dcp1.0-nlb0` may well be dispatched to a node running the nlb0 accelerated function on an Aria10.

Solution:

1. Modify the FPGA plugin to expose both AF and interface IDs in resource names in "preprogrammed" mode (currently only AF ID is exposed).
3. Modify AcceleratedFunction CRDs to contain info on the hardware the accelerated function is intended to run on (interface ID) and the required mode of the FPGA plugin. So that a cluster admin would have the possibility to configure the webhook to operate with plugins in both modes.

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acceleratorfunctions.fpga.intel.com
spec:
  group: fpga.intel.com
  version: v1
  scope: Namespaced
  names:
    plural: acceleratorfunctions
    singular: acceleratorfunction
    kind: AcceleratorFunction
    shortNames:
    - af
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            afuId:
              type: string
              pattern: '^[0-9a-f]{8,128}$'
            interfaceId:
              type: string
              pattern: '^[0-9a-f]{8,128}$'
            mode:
              type: string
              pattern: '^preprogrammed|orchestrated$'
```
4. Modify the webhook not to accept `-mode` option and to translate requested resources using AcceleratedFunction CRDs only in the new format.

The format of resource names visible to a user is not changed. Basically the format can be anything, but it's expected to be in the form `<hardware>-<firmware_release>-<accelerated_function>`, e.g. `arria10-dcp1.1-nlb0`.
