### ISSUE TITLE
OCP: Merge SGX HW feature detecting fixing into OCP 

### ISSUE THREAD

**Issue by Walnux** [intel/intel-device-plugins-for-kubernetes#780]
This SGX HW feature detecting issue is resolved in intel-device-plugins operator upstream see: https://github.com/intel/intel-device-plugins-for-kubernetes/issues/739
and NFD upstream see:  https://github.com/kubernetes-sigs/node-feature-discovery/commit/8a394346598e2be3fc769ed29f38547784a212f1

We need to make sure this fix can be merged into the NFD-Operator as well as OCP

NFD upstream is cutting 0.10.0 release including this fix.
https://github.com/kubernetes-sigs/node-feature-discovery/issues/678

**Comment by Walnux** [comment]
The NFD upstream fixing is:
https://github.com/kubernetes-sigs/node-feature-discovery/commit/8a394346598e2be3fc769ed29f38547784a212f1

**Comment by Walnux** [comment]
According to https://github.com/openshift/cluster-nfd-operator/issues/230
@ArangoGutierrez  will merge this fix into OCP-4.9 and OCP-4.10

**Comment by Walnux** [comment]
@ArangoGutierrez
NFD-0.10.0 upstream has been released. Could you let us know the statutes in OCP-4.9 and 4.10?
Looks like in OCP-4.9 the latest NFD-operator version is 4.9.0-202111171831.
Thanks!

**Comment by Walnux** [comment]
@ArangoGutierrez since we are working on the integration testing, NFD and NFD operator is the most important part. Is it possible to share us the bundle image, so we can install it on 4.9 manually? So we can verify it as early as possible. Thanks!

**Comment by ArangoGutierrez** [comment]
Backporting such commit into 4.9 will require porting too much, a workaround, tested, is to set `quay.io/openshift/origin-node-feature-discovery:4.10` on the image field of the CR 

```yaml
apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  #instance: "" # instance is empty by default
  #labelWhiteList: ""
  #extraLabelNs:
  #  - "example.com"
  #resourceLabels:
  #  - "example.com/resource"
  operand:
    image: quay.io/openshift/origin-node-feature-discovery:4.10
    imagePullPolicy: Always
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
```
