### ISSUE TITLE
admission webhook "fpga.mutator.webhooks.intel.com" denied the request: environment variable 'FPGA_AFU_1' is not allowed

### ISSUE THREAD

**Issue by belanasaikiran** [intel/intel-device-plugins-for-kubernetes#863]
I was trying to run one of the example deployment ( `test-fpga-region.yaml` ) on my cluster with FPGAs.
Iam getting the following error when running the app after programming the devices:

```
saikiran@server1:~/Kubernetes/fpga-device-plugin/intel-device-plugins-for-kubernetes/demo$ k apply -f test-fpga-orchestrated.yaml
Error from server: error when creating "test-fpga-orchestrated.yaml": admission webhook "fpga.mutator.webhooks.intel.com" denied the request: environment variable 'FPGA_AFU_1' is not allowed
```

I have followed the following guide:
[https://asciinema.org/a/sUnLNwpazbUXKdpC66g09W5w1](https://asciinema.org/a/sUnLNwpazbUXKdpC66g09W5w1)

here's the result of programmed devices:
```
> cat /sys/class/*/*/*/afu_id                                                                                                                                                     
d8424dc4a4a3c413f89e433683f9040b                                                                                                                                                  
d8424dc4a4a3c413f89e433683f9040b 
```

please can you help me resolve this issue/errors

**Comment by mythi** [comment]
@bart0sh any ideas?

**Comment by rojkov** [comment]
IIRC the webhook denies new pods if they set FPGA_AFU_* (and FPGA_REGION_*) env variables. These variables are supposed to be set by the webhook itself, not a user. It sounds like `test-fpga-orchestrated.yaml` for some reason sets the variable. Though in my copy of the repo this file doesn't touch ENV at all.

What's the content of the failing YAML?

**Comment by bart0sh** [comment]
@belanasaikiran Have you modified test-fpga-orchestraded.yaml somehow? Which project branch did you use for your experiments? Did you build images locally or downloaded them from the dockerhub?

**Comment by belanasaikiran** [comment]
Thank you @mythi @rojkov @bart0sh  for replying,

@rojkov, I haven't set any variables with `user`, I have followed the user guide. Here is the content of the file `test-fpga-orchestrated.yaml`

```
apiVersion: v1
kind: Pod
metadata:
  name: test-fpga-orchestrated
spec:
  containers:
  - name: test-container
    image: intel/opae-nlb-demo:devel
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
          [IPC_LOCK]
    resources:
      limits:
        fpga.intel.com/arria10.dcp1.2-nlb3-orchestrated: 1
        cpu: 1
        hugepages-2Mi: 20Mi

  restartPolicy: Never
```
Is there anything I need to change in this file ?


@bart0sh, I haven't modified the contents of `test-fpga-orchestrated.yaml`.
I am using the current main branch for testing and I have build images locally as per the instructions provided in Documentation (haven't modified).

Please can you help me resolving the issue so.
